const menuItems = [
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
  { image: "/images/burger.png" },
];
